- hosts: client
  sudo: no
  gather_facts: no
  remote_user: root
    
  tasks:
    - service: name={{ item }} state=stopped
      with_items:
        - beegfs-client
        - beegfs-helperd
      failed_when: false
        
    - name: remove beegfs rpm
      yum: name="{{ item }}" state=absent
      with_items:
        - beegfs-utils
        - beegfs-helperd
        - beegfs-client
        - beegfs-opentk-lib
        - beegfs-common
      failed_when: false
      
- hosts: storage
  sudo: no
  gather_facts: no
  remote_user: root
  
  tasks:
    - service: name=beegfs-storage state=stopped
      failed_when: false
      
    - name: remove beegfs rpm
      yum: name="{{ item }}" state=absent
      with_items:
        - beegfs-utils
        - beegfs-helperd
        - beegfs-storage
        - beegfs-opentk-lib
        - beegfs-common
      failed_when: false
      
#    - file: path="{{ storage_dir }}" state=absent
            
            
- hosts: meta
  sudo: no
  gather_facts: no
  remote_user: root
  
  tasks:
    - service: name=beegfs-meta state=stopped
      failed_when: false
      
    - name: remove beegfs rpm
      yum: name="{{ item }}" state=absent
      with_items:
        - beegfs-utils
        - beegfs-helperd
        - beegfs-meta
        - beegfs-opentk-lib
        - beegfs-common
      failed_when: false

    - file: path="{{ meta_dir }}" state=absent

- hosts: mgmt
  sudo: no
  gather_facts: no
  remote_user: root
  
  tasks:
    - service: name=beegfs-mgmtd state=stopped
      failed_when: false
      
    - name: remove beegfs rpm
      yum: name="{{ item }}" state=absent
      with_items:
        - beegfs-utils
        - beegfs-helperd
        - beegfs-admon
        - beegfs-mgmtd
        - beegfs-opentk-lib
        - beegfs-common
      failed_when: false
      
    - file: path="{{ mgmtd_dir }}" state=absent
      
