- hosts: storage
  gather_facts: no
  remote_user: root

  tasks:
    - service: name=beegfs-storage state=stopped

- hosts: meta
  gather_facts: no
  remote_user: root

  tasks:
    - service: name=beegfs-meta state=stopped

- hosts: mgmt
  gather_facts: no
  remote_user: root

  tasks:
    - service: name=beegfs-mgmtd state=restarted

- hosts: meta
  gather_facts: no
  remote_user: root

  tasks:
    - service: name=beegfs-meta state=started

- hosts: storage
  gather_facts: no
  remote_user: root

  tasks:
    - service: name=beegfs-storage state=started

