- name: remove unnecessary rpm
  yum: name={{ item }} state=absent
  with_items:
    - beeond
    - beegfs-client
    - beegfs-client-devel
    - beegfs-admon

- name: tune net.ipv4.neigh.default.gc_thresh1,2 & 3, really important

- name: install beegfs rpm
  yum: name={{ item }}
  with_items:
    - beegfs-mgmtd
    - beegfs-helperd
    - beegfs-utils

- lineinfile: dest=/etc/beegfs/beegfs-mgmtd.conf regexp='^storeMgmtdDirectory' line='storeMgmtdDirectory = {{ mgmtd_dir }}'      
- lineinfile: dest=/etc/beegfs/beegfs-mgmtd.conf regexp='^connInterfacesFile' line='connInterfacesFile = /etc/beegfs/interface'      
- lineinfile: dest=/etc/beegfs/beegfs-mgmtd.conf regexp='^tuneNumWorkers' line='tuneNumWorkers = {{ num_workers }}'

- lineinfile: dest=/etc/beegfs/beegfs-mgmtd.conf regexp='^quotaEnableEnforcement' line='quotaEnableEnforcement = true'                                                                                                                                                             
  when: quota_enforce|bool                                                                                                                                                                                                                                 
- lineinfile: dest=/etc/beegfs/beegfs-mgmtd.conf regexp='^quotaUpdateIntervalMin' line='quotaUpdateIntervalMin = 10'                                                                                                                                                               
  when: quota_enforce|bool                                                                                                                                                                                                                                                          
- lineinfile: dest=/etc/beegfs/beegfs-mgmtd.conf regexp='^quotaQueryType' line='quotaQueryType = system'                                                                                                                                                                           
  when: quota_enforce|bool                                                                                                                                                                                                                                                         

- file: path=/etc/beegfs/interface state=absent
- lineinfile: dest=/etc/beegfs/interface line='ib0' create=yes
  when: ansible_ib0.device is defined

- lineinfile: dest=/etc/beegfs/interface line='{{ item }}' create=yes
  when: ansible_{{ item }}.device is defined
  with_items: "{{ network_interface }}"
  
- command: "/opt/beegfs/sbin/beegfs-setup-mgmtd -p {{ mgmtd_dir }}"
  failed_when: false

- service: name=beegfs-mgmtd state=started enabled=yes
